### ISSUE TITLE
PBC pinout

### ISSUE THREAD

**Issue by xile6** [Z3BRO/Flipper-Zero-RBG-Backlight#1]
Hi i would like to know how the PBC controls the RGB. I am looking to simple hardwired RGB leds in.
From looking at the PBC i only see ground, power and pin A7, which i am guessing is power.

How is these controlling the colors of the led? what am i missing.

**Comment by Z3BRO** [comment]
You have to flash a cfw, Pin A7 is connected to the controller pad on the
pcb.

**Comment by Z3BRO** [comment]
A fix is being developed where you use a internal line instead of the gpio pin.
