### ISSUE TITLE
Zip file missing drill file

### ISSUE THREAD

**Issue by RChadwick7** [Z3BRO/Flipper-Zero-RBG-Backlight#12]
I tried having LED-PCB_GBR.zip made at Oshpark and JLCPCB, both said .DRL file is missing and wouldn't make the board. The LED-PCB_GBR_WITH_RESISTOR.zip does have rgb-NPTH.DRL and rgb-NPTH.DRL . Can the drill files be made available for the working board?? Better yet, can the KiCad files be made available?

**Comment by Z3BRO** [comment]
I can make the KiCad files available in a few hours, when i am at computer.
