### ISSUE TITLE
Doesn't fit?

### ISSUE THREAD

**Issue by Fexiven** [Z3BRO/Flipper-Zero-RBG-Backlight#15]
Can it be that there are different screens because the PCB doesn't fit at all, sadly now the screen is destroyed :(

Or can I just remove the resistor?

![PXL_20230723_092253372](https://github.com/Z3BRO/Flipper-Zero-RGB-Backlight/assets/48439988/b048a987-2476-4f35-8615-ffeab2f4d3d3)

**Comment by Z3BRO** [comment]
The RGB Backlight mod is not yet compatible with the R04(02) model of flipper, you can use a dremel or flush cutters to modify the display to make it fit.

**Comment by Fexiven** [comment]
Quick update, yesterday i tried to fix my flipper with the RGB Mod, and indeed with a dremel it worked perfectly.
