### ISSUE TITLE
Unclear Patch instructions 

### ISSUE THREAD

**Issue by FoxLy1312** [Z3BRO/Flipper-Zero-RBG-Backlight#3]
i stuck at procedure of patching the RGB-software to latest @RogueMaster repo, any help?

**Comment by jbohack** [comment]
drag and drop [this](https://github.com/Z3BRO/Flipper-Zero-RBG-Backlight/tree/main/Firmware%20Patches/RGB%20FW%20FILES) directory in to the root directory of rogue master firmware and then run

.\fbt.cmd updater_package

feel free to reopen if you have anymore questions :)
