### ISSUE TITLE
great hack, screen?

### ISSUE THREAD

**Issue by eried** [Z3BRO/Flipper-Zero-RBG-Backlight#4]
Hey! very nice hack, I wonder if you discovered where flipper got their screens in all this research. I guess it is this model https://www.displayfuture.com/Display/datasheet/monographic/ERC12864-4.pdf with a different attachment

Any guess?

**Comment by Z3BRO** [comment]
iirc, the flipper teams has their screens custom made for the flipper; you
should be able to buy displays from FlipperDevices within the next few
months as they are opening a parts shop. Hope that answers your question!
