### ISSUE TITLE
Little glow ups

### ISSUE THREAD

**Issue by FoxLy1312** [Z3BRO/Flipper-Zero-RBG-Backlight#9]
Sometimes the backlight switches to a week Red or blue tone instead of turning off.

kind of lit somehow 🔥

![4BCED45E-7249-4949-8C1F-55EA11687D8B](https://user-images.githubusercontent.com/110127890/229958134-11282b40-39d9-47de-9010-714eec65d5df.jpeg)

**Comment by jbohack** [comment]
should be fixed now. feel free to reopen if you notice the problem again :)
